
---
#
# install curator tool for managing elasticsearch
#

- name: Down and install the Public Signing key
  command: wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  when: install_curator_tool
- name: Save the repository definition to /etc/apt/sources.list.d/curator.list
  command: echo "deb http://packages.elastic.co/curator/4/debian stable main" | sudo tee -a /etc/apt/sources.list.d/curator.list
  when: install_curator_tool

- apt: update_cache=yes

- name: Install curator and python-setuptools
  apt: name={{ item }} state=present
  become: true
  with_items:
    - python-elasticsearch-curator
    - python-setuptools
  when: install_curator_tool
